### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kieranmoran3** [xLasercut/nhsuk-frontend-vue#5]
Apologies for leaving this as an issue - can't see another way of asking.

I notice that the library references the MIT front end MIT license, but doesn't have one itself.

Can I ask what license this is (and suggest putting a license file in)? Just wanted to double check before I use it.

**Comment by kieranmoran3** [comment]
I should clarify - I'm asking what license your port is, not about the NHS front end original license.

**Comment by xLasercut** [comment]
my license is the same as NHS frontend. I have added a license file.
